# Generated by Django 4.1.5 on 2023-01-20 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='MeterMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('kwh_consumption', models.IntegerField()),
                ('consumption_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption', to='meter_api.meter')),
            ],
        ),
    ]
